[INIT] Setup Kerrighed's RPC net devices at boot time
Use the new sysfs interface to only setup Kerrighed's RPC net devices
after Kerrighed's hotplug configuration is done. This is required to
enable fully automatic cluster start.

Signed-off-by: Louis Rilling <louis.rilling@kerlabs.com>

diff --git a/tools-host/kerrighed-host.init b/tools-host/kerrighed-host.init
--- a/tools-host/kerrighed-host.init
+++ b/tools-host/kerrighed-host.init
@@ -88,6 +88,14 @@ d_start() {
 	log_progress_msg "(failed)"; STATUS=1
     fi
 
+    log_progress_msg "net_devices"
+    for dev in $NET_DEVICES; do
+	log_progress_msg "$dev"
+	if ! echo $dev > /sys/kerrighed/net_devices; then
+	    log_progress_msg "(failed)"; STATUS=1
+	fi
+    done
+
     if test "$(cat /sys/kerrighed/node_id)" = "$BOOT_ID"; then
 	log_progress_msg "container"
 	if ! d_start_container; then
