krgboot_helper: Run hooks before and after creating the Kerrighed container
This commit introduce two new directories
/etc/kerrighed/krgboot_helper-pre.d and
/etc/kerrighed/krgboot_helper-post.d to contain user-defined scripts to be
called before (resp.) after creating the Kerrighed container.

Scripts called in the "post" phase are passed the PID of the new container
init in argument.

Such scripts should help users customizing the setup of the Kerrighed
container.

Signed-off-by: Louis Rilling <louis.rilling@kerlabs.com>

diff --git a/tools-host/krgboot_helper.in b/tools-host/krgboot_helper.in
--- a/tools-host/krgboot_helper.in
+++ b/tools-host/krgboot_helper.in
@@ -2,7 +2,10 @@
 
 set -e
 
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
+
 SYS_DIR=/sys/kerrighed/hotplug
+RUN_DIR=/var/run/kerrighed
 KRGBOOT=@sbindir@/krgboot
 
 error() {
@@ -50,4 +53,24 @@ if [ "$ISOLATE_USER" -ne 0 ]; then
 	NS_ARGS="$NS_ARGS -U"
 fi
 
-exec $KRGBOOT $NS_ARGS -- $CLUSTER_INIT_HELPER
+rm -rf $RUN_DIR
+mkdir -p $RUN_DIR
+TEMPPID=$RUN_DIR/krginit-pid.$$
+mkfifo $TEMPPID || error "Cannot create temporary PID file"
+
+run-parts -- @sysconfdir@/kerrighed/krgboot_helper-pre.d
+
+# The kernel expects that the Kerrighed container will be cloned from this very
+# process, so KRGBOOT must be exec()'ed, which does not allow us to run post
+# scripts from this process.
+# Instead launch a trigger, which synchronizes with container creation through a
+# FIFO.
+(
+	read PID < $TEMPPID
+	rm "$TEMPPID"
+	[ -z "$PID" ] && exit 1
+
+	run-parts --arg=$PID -- @sysconfdir@/kerrighed/krgboot_helper-post.d
+) &
+
+exec $KRGBOOT $NS_ARGS -w "$TEMPPID" -- $CLUSTER_INIT_HELPER
