Make update-rc.d fails without error if rc.d updater is not found in the env. It is often the case in chroot envs.

diff --git a/scripts/update-rc.d/debian b/scripts/update-rc.d/debian
--- a/scripts/update-rc.d/debian
+++ b/scripts/update-rc.d/debian
@@ -2,11 +2,13 @@
 #
 # update-rc.d Register kerrighed service for Debian-like distros
 #
-# Author:	Jean Parpaillon <jean.parpaillon@kerlab.com>
+# Author:	Jean Parpaillon <jean.parpaillon@kerlabs.com>
 #
 # Copyright:    INRIA-IRISA - 2006-2007
-#               Kerlabs 2007
+#               Kerlabs 2007-2009
 #
+set -e
+
 PROGRAM=$(basename ${0})
 SCRIPT=/usr/sbin/update-rc.d
 # Have a look at /etc/rcS.d/README to understand
@@ -33,7 +35,7 @@ then
 fi
 
 ARGUMENTS="$(getopt --longoptions install,remove,chroot: --name=${PROGRAM} --options irc: --shell sh -- "${@}")"
-if [ "${?}" != "0" ] 
+if [ "${?}" != "0" ]
 then
     Error "Error parsing options"
     exit 1
@@ -41,6 +43,7 @@ fi
 
 eval set -- "${ARGUMENTS}"
 
+CHROOT_DIR=
 while true
 do
     case "${1}" in
@@ -53,7 +56,8 @@ do
 	    shift
 	    ;;
 	--chroot|-c)
-	    CHROOT="chroot ${2}"
+	    CHROOT_DIR="${2}"
+	    CHROOT="chroot ${CHROOT_DIR}"
 	    shift 2
 	    ;;
 	--)
@@ -67,11 +71,15 @@ do
     esac
 done
 
+if test ! -x ${CHROOT_DIR}${SCRIPT}; then
+    echo "Missing ${CHROOT_DIR}${SCRIPT}, aborting..."
+    exit 0
+fi
+
 if test "${action}" = "install"; then
     i_install
 elif test "${action}" = "remove"; then
     i_remove
 fi
-    
-  
+
 exit 0
